<h1>Pravidla stránek</h1>
<hr>
<ul class="list-group">
    <li class="text-justify list-group-item list-group-item-danger">Navštívením našich stránek www.hodnotimefilmy.cz potvrzujete, že jste si vědomi všech níže uvedených skutečností a že podle nich budete postupovat.
    <li class="text-justify list-group-item">Vlastníkem a provozovatelem internetových stránek www.ervpojistovna.cz je ERV Evropská pojišťovna, a. s. (dále jen „provozovatel“). Veškerý obsah těchto stránek včetně textů, designu, technických náčrtů, grafiky, vyobrazení a uspořádání souborů je chráněn autorským právem. Tyto materiály lze užívat výhradně pro osobní a nekomerční účely. Obsah a jakoukoli část těchto stránek lze uchovávat, upravovat a šířit jen se souhlasem provozovatele a toto užití musí obsahovat odkaz na autorské právo provozovatele. Označení provozovatele je řádně registrovanou ochrannou známkou, k níž se vztahují odpovídající právní předpisy. Veškerá loga použitá na stránkách jsou registrována příslušnými subjekty.
    <li class="text-justify list-group-item">Provozovatel neodpovídá za jakékoliv hmotné či nehmotné škody vzniklé v souvislosti s užitím či neužitím informací zveřejněných na těchto stránkách. Veškeré informace na stránkách jsou poskytovány při nejlepším vědomí a svědomí provozovatele, který nenese odpovědnost za jejich úplnost či technickou přesnost. Provozovatel rovněž neodpovídá za jakoukoli škodu či poškození virem při stahování údajů ze stránek. Provozovatel si vyhrazuje právo stránky a informace na nich uvedené upravovat či měnit bez předchozího upozornění.
    <li class="text-justify list-group-item">Kliknutím na některé odkazy lze opustit tyto stránky. Stránky jiných subjektů, na něž odkazují stránky provozovatele, nejsou pod kontrolou provozovatele, a ten tudíž neodpovídá za jejich obsah či vzhled.
    <li class="text-justify list-group-item">Veškeré údaje získané od návštěvníků stránek jsou považovány za osobní a jsou chráněny podle zákona O ochraně osobních údajů č. 101/2000 Sb., ve znění pozdějších dodatků a předpisů. Tyto osobní údaje jsou využívány pouze pro potřebu Provozovatele stránek a nebudou poskytnuty žádné třetí straně.
    <li class="text-justify list-group-item">Od registrovaných návštěvníků požadujeme jen údaje v rozsahu nezbytném pro registraci. Získané osobní údaje jsou zabezpečeny proti zneužití.
    <li class="text-justify list-group-item">Registrovaný návštěvník je povinen zadávat a udržovat data o své osobě pravdivá, aktuální a správná. Svou registraci může také kdykoliv zrušit. Zrušení registrace znamená kompletní odstranění všech dat o uživateli, ale i ztrátu všech výhod a uložených dat s touto registrací spojené.
</ul>

